// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  A: string;
  B: string;
  Container: string;
  Employeecontainer: string;
  LBAN: string;
  UserImg: string;
  UserImg1: string;
  allocate: string;
  bbody: string;
  blob: string;
  blob2: string;
  blob3: string;
  blob4: string;
  btn: string;
  container: string;
  container2: string;
  dash: string;
  dashboard: string;
  digit: string;
  file: string;
  filesvg: string;
  firstSection: string;
  icon: string;
  icons: string;
  imgContainer: string;
  imgContainer2: string;
  imgbtn: string;
  line: string;
  lineContainer: string;
  maincontainer: string;
  num: string;
  pending: string;
  portal: string;
  secondSection: string;
  shadow: string;
  shadow1: string;
  shadow2: string;
  sideb: string;
  sidebar: string;
  testing: string;
  text: string;
  text1: string;
  textContainer: string;
  userLoggedIn: string;
  welcome: string;
}
const cssExports: CssExports;
export default cssExports;
