// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Container': string;
  'imgContainer': string;
  'imgContainer2': string;
  'maincontainer': string;
  'portal': string;
  'text': string;
  'textContainer': string;
}
const cssExports: CssExports;
export default cssExports;
