// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'card': string;
  'cardIcon': string;
  'cardText': string;
  'circle': string;
}
const cssExports: CssExports;
export default cssExports;
